<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to modules' => 'Retour aux modules',
    'Get a list' => 'Liste',
    'Last <strong>spaces</strong> created' => 'Derniers <strong>espaces</strong> créés',
    'Last spaces Module Configuration' => 'Configuration module derniers espaces créés',
    'Save' => 'Sauvegarder',
    'The number of last spaces that will be shown.' => 'Le nombre d\'espace à afficher',
    'You may configure the number spaces to be shown.' => 'Vous pouvez configurer le nombre d\'espace à afficher',
];
